### ISSUE TITLE
Strip fields / Add queris

### ISSUE THREAD

**Issue by birdmedia** [codefog/contao-member_export#1]
Hi Kamil,

is there an option to remove specific fields in the export file? Some fields containing technical information (login count, session etc.) could be removed.

I would also like to add some queries to export different member groups, e.g. groups LIKE '%"20"%'. Is there an option to do so?

**Comment by qzminski** [comment]
You can provide your own export features by adding or overriding the existing export formats:

https://github.com/codefog/contao-member_export/blob/master/config/config.php#L31
