### ISSUE TITLE
Ungültiges Anfrage-Token / Invalid request token

### ISSUE THREAD

**Issue by Funbug** [codefog/contao-member_export#14]
I get the error message "Ungültiges Anfrage-Token" when trying to export the member data using Contao 4.13.40. Anything I can do to fix that?

**Comment by landzone21** [comment]
I get the same error in Contao 4.13.43. What can we do to fix that?

**Comment by herrrilke** [comment]
same here (C 4.13.40)

**Comment by qzminski** [comment]
This should be fixed in 2.4.1 which I have just released.

**Comment by herrrilke** [comment]
works perfectly! thank you!

**Comment by Funbug** [comment]
Thanks! ❤️
