### ISSUE TITLE
Exclude not working?

### ISSUE THREAD

**Issue by lennier83** [codefog/contao-member_export#4]
Hello Codefog.
I am just testing the Exclude Formfields. And it looks like, it does not work.
```
<?php
$excludedFields = ['tstamp', 'password', 'session', 'member_gbj'];

foreach ($excludedFields as $field) {
    $GLOBALS['TL_DCA']['tl_member']['fields'][$field]['eval']['memberExportExcluded'] = true;
}
```

A tl_member.php is in the right path like written in the doku.
Do you see a mistake somewhere?

Thank you

**Comment by qzminski** [comment]
Did you rebuild the cache?

**Comment by lennier83** [comment]
Yes. Via contao-Manager and manuell -> var/cache/prod
tl_member.php has 644

**Comment by qzminski** [comment]
It works just fine for me. Please ensure that your file is in correct destination. You can also add a debug code there to see if it's even being considered:

```php
var_dump('test');exit;
```

**Comment by lennier83** [comment]
Sorry. Still was the dev-Version. Updated the extension. Works :-)
