### ISSUE TITLE
The service "codefog_member_export.controller" was not found

### ISSUE THREAD

**Issue by chunkyrook** [codefog/contao-member_export#6]
Hi & thanks for this extension! When I click the export button, I get the following error message:
The service "codefog_member_export.controller" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services

Any idea what may cause this? (Contao 4.6.6) Thanks for your help!

**Comment by qzminski** [comment]
This should be fixed in 2.1.1 which has been just released.

**Comment by chunkyrook** [comment]
Works now, thanks a lot!
